### ISSUE TITLE
(python2) Install error: TypeError: 'package' must be a string (dot-separated), list, or tuple

### ISSUE THREAD

**Issue by codekoala** [Bahus/uwsgi_tasks#2]
I received the following error when running `pip2 install uwsgi-tasks`:

```
Collecting uwsgi-tasks
  Downloading uwsgi-tasks-0.4.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (from uwsgi-tasks)
Installing collected packages: uwsgi-tasks
  Running setup.py install for uwsgi-tasks
    Complete output from command /usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GlGiOE/uwsgi-tasks/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-C7jHzB-record/install-record.txt --single-version-externally-managed --compile:
    Pandoc not found, tried: (u'/usr/local/bin/pandoc', u'/usr/bin/pandoc')
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GlGiOE/uwsgi-tasks/setup.py", line 60, in <module>
        install_requires=['six'],
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/build_py.py", line 46, in run
        self.build_packages()
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/usr/lib/python2.7/site-packages/setuptools/command/build_py.py", line 65, in build_module
        package)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple

    ----------------------------------------
    Command "/usr/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GlGiOE/uwsgi-tasks/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-C7jHzB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-GlGiOE/uwsgi-tasks
```

**Comment by codekoala** [comment]
It does not fail for Python 3.4

**Comment by Bahus** [comment]
Oh, It was my falt to use distutils instead of setuptools. Could you please try release 0.4.4 from pypi? The issue should be fixed now.

**Comment by codekoala** [comment]
I tried it for both python 2 and 3, and both worked perfectly. Thanks!
