### ISSUE TITLE
Using uwsgi_tasks on flat django project structure

### ISSUE THREAD

**Issue by dmchmk** [Bahus/uwsgi_tasks#6]
Hi!

Is there a proper way to use `uwsgi_tasks` on a flat django project structure?

In docs there's a following example:

    ├── project/
    │   ├── venv/  <-- your virtual environment is placed here
    │   ├── my_project/  <-- Django project (created with "startproject" command)
    │   │   ├── apps/
    │   │   │   ├── index/  <-- Single Django application ("startapp" command)
    │   │   │   │   ├── __init__.py
    │   │   │   │   ├── admin.py
    │   │   │   │   ├── models.py
    │   │   │   │   ├── tasks.py
    │   │   │   │   ├── tests.py
    │   │   │   │   ├── views.py
    │   │   │   ├── __init__.py
    │   │   ├── __init__.py
    │   │   ├── settings.py
    │   │   ├── urls.py
    │   ├── spooler/  <-- spooler files are created here

But what should we do when we have something like this:

    ├── venv/  <-- your virtual environment is placed here
    ├── spooler/  <-- spooler files are created here
    ├── project/
    │   ├── index/  <-- Single Django application ("startapp" command)
    │   │   ├── __init__.py
    │   │   ├── admin.py
    │   │   ├── models.py
    │   │   ├── tasks.py
    │   │   ├── tests.py
    │   │   ├── views.py
    │   │   ├── __init__.py
    │   ├── my_project/  <-- Django project (created with "startproject" command)
    │   │   ├── __init__.py <-- here I've imported set_uwsgi_callbacks
    │   │   ├── settings.py
    │   │   ├── utils.py <-- here I have the @task decorated function
    │   │   ├── urls.py
    │   ├── manage.py
is there a way for proper usage of the `uwsgi_tasks` in such configuration?

Thanks a lot!

Right now I'm getting this error:

```
Traceback (most recent call last):
  File "/var/venv/project_name/lib64/python3.6/site-packages/uwsgi_tasks/utils.py", line 23, in import_by_path
    module = import_module(module_path)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_project.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/tasks.py", line 70, in manage_spool_request
    return task.execute_now()
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/tasks.py", line 361, in execute_now
    result = super(SpoolerTask, self).execute_now()
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/tasks.py", line 218, in execute_now
    setattr(self.function, self.attr_name, self)
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/tasks.py", line 209, in function
    self._function = load_function(self.function_name)
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/tasks.py", line 62, in load_function
    return import_by_path(func_name)
  File "/var/venv/venv_name/lib64/python3.6/site-packages/uwsgi_tasks/utils.py", line 25, in import_by_path
    raise ImportError('Failed to import "{}" - {}'.format(dotted_path, ex))
ImportError: Failed to import "my_project.utils.email_send" - No module named 'my_project.utils'
```

**Comment by Bahus** [comment]
Oh, I'm sorry for so late response, I haven't received a notification. The issue is most probably related to you PYTHONPATH settings. Make sure that you have the following lines in your uwsgi configuration:

```ini
pythonpath=../project/
```

Try to experiment and add the following line:

```ini
spooler-python-import=my_project
```

Also verify that you don't have a circular imports in `my_project.utils` file.
